server:
  port: 8080
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/loans?createDatabaseIfNotExist=true
    username: root
    password: root
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
